In [36]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, classification_report, confusion_matrix

In [37]:
f_train = pd.read_csv('./data/train.csv')
f_test = pd.read_csv('./data/test.csv')

In [38]:
f_train.describe()

,Unnamed: 0,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
count,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103594.000000
mean,51951.500000,64924.210502,39.379706,1189.448375,2.729683,3.060296,2.756901,2.976883,3.202129,3.250375,3.439396,3.358158,3.382363,3.351055,3.631833,3.304290,3.640428,3.286351,14.815618,15.178678
std,29994.645522,37463.812252,15.114964,997.147281,1.327829,1.525075,1.398929,1.277621,1.329533,1.349509,1.319088,1.332991,1.288354,1.315605,1.180903,1.265396,1.175663,1.312273,38.230901,38.698682
min,0.000000,1.000000,7.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,25975.750000,32533.750000,27.000000,414.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,2.000000,0.000000,0.000000
50%,51951.500000,64856.500000,40.000000,843.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,3.000000,4.000000,3.000000,0.000000,0.000000
75%,77927.250000,97368.250000,51.000000,1743.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,5.000000,4.000000,12.000000,13.000000
max,103903.000000,129880.000000,85.000000,4983.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1592.000000,1584.000000

In [39]:
f_train.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [40]:
f_train.isna().sum()

Unnamed: 0                             0
id                                     0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             310
satisfaction                           0
dtype: int64

In [41]:
f_test.isna().sum()

Unnamed: 0                            0
id                                    0
Gender                                0
Customer Type                         0
Age                                   0
Type of Travel                        0
Class                                 0
Flight Distance                       0
Inflight wifi service                 0
Departure/Arrival time convenient     0
Ease of Online booking                0
Gate location                         0
Food and drink                        0
Online boarding                       0
Seat comfort                          0
Inflight entertainment                0
On-board service                      0
Leg room service                      0
Baggage handling                      0
Checkin service                       0
Inflight service                      0
Cleanliness                           0
Departure Delay in Minutes            0
Arrival Delay in Minutes             83
satisfaction                          0
dtype: int64

In [42]:
import numpy as np

f_train = f_train.dropna()
f_test = f_test.dropna()

f_train['satisfactionn'] = np.where(f_train['satisfaction'] == 'satisfied', 1, 0)
f_test['satisfactionn'] = np.where(f_test['satisfaction'] == 'satisfied', 1, 0)

f_train.head(20)

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction,satisfactionn
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,4,3,4,4,5,5,25,18.0,neutral or dissatisfied,0
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,5,3,1,4,1,1,6.0,neutral or dissatisfied,0
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,4,3,4,4,4,5,0,0.0,satisfied,1
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,5,3,1,4,2,11,9.0,neutral or dissatisfied,0
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,4,4,3,3,3,0,0.0,satisfied,1
5,5,111157,Female,Loyal Customer,26,Personal Travel,Eco,1180,3,4,...,3,4,4,4,4,1,0,0.0,neutral or dissatisfied,0
6,6,82113,Male,Loyal Customer,47,Personal Travel,Eco,1276,2,4,...,3,3,4,3,5,2,9,23.0,neutral or dissatisfied,0
7,7,96462,Female,Loyal Customer,52,Business travel,Business,2035,4,3,...,5,5,5,4,5,4,4,0.0,satisfied,1
8,8,79485,Female,Loyal Customer,41,Business travel,Business,853,1,2,...,1,2,1,4,1,2,0,0.0,neutral or dissatisfied,0
9,9,65725,Male,disloyal Customer,20,Business travel,Eco,1061,3,3,...,2,3,4,4,3,2,0,0.0,neutral or dissatisfied,0
10,10,34991,Female,disloyal Customer,24,Business travel,Eco,1182,4,5,...,3,3,5,3,5,2,0,0.0,neutral or dissatisfied,0
11,11,51412,Female,Loyal Customer,12,Personal Travel,Eco Plus,308,2,4,...,1,2,5,5,5,1,0,0.0,neutral or dissatisfied,0
12,12,98628,Male,Loyal Customer,53,Business travel,Eco,834,1,4,...,1,1,3,4,4,1,28,8.0,neutral or dissatisfied,0
13,13,83502,Male,Loyal Customer,33,Personal Travel,Eco,946,4,2,...,4,5,2,2,2,4,0,0.0,satisfied,1
14,14,95789,Female,Loyal Customer,26,Personal Travel,Eco,453,3,2,...,4,3,2,2,1,2,43,35.0,neutral or dissatisfied,0
15,15,100580,Male,disloyal Customer,13,Business travel,Eco,486,2,1,...,2,1,4,1,3,4,1,0.0,neutral or dissatisfied,0
16,16,71142,Female,Loyal Customer,26,Business travel,Business,2123,3,3,...,5,3,4,5,4,4,49,51.0,satisfied,1
17,17,127461,Male,Loyal Customer,41,Business travel,Business,2075,4,4,...,5,5,5,3,5,5,0,10.0,satisfied,1
18,18,70354,Female,Loyal Customer,45,Business travel,Business,2486,4,4,...,5,5,5,3,5,4,7,5.0,satisfied,1
19,19,66246,Male,Loyal Customer,38,Personal Travel,Eco,460,2,3,...,1,2,4,3,2,5,17,18.0,neutral or dissatisfied,0

In [43]:

f_train.nunique()

Unnamed: 0                           103594
id                                   103594
Gender                                    2
Customer Type                             2
Age                                      75
Type of Travel                            2
Class                                     3
Flight Distance                        3802
Inflight wifi service                     6
Departure/Arrival time convenient         6
Ease of Online booking                    6
Gate location                             6
Food and drink                            6
Online boarding                           6
Seat comfort                              6
Inflight entertainment                    6
On-board service                          6
Leg room service                          6
Baggage handling                          5
Checkin service                           6
Inflight service                          6
Cleanliness                               6
Departure Delay in Minutes              445
Arrival Delay in Minutes                455
satisfaction                              2
satisfactionn                             2
dtype: int64

In [46]:

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier

X_train = f_train.drop(columns=['satisfaction', 'satisfactionn'])
y_train = f_train['satisfactionn']
X_test = f_test.drop(columns=['satisfaction', 'satisfactionn'])
y_test = f_test['satisfactionn']

numeric_features = X_train.select_dtypes(include=[np.number]).columns.tolist()
categorical_features = X_train.select_dtypes(include=['object']).columns.tolist()

numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())  # Standardisatie
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))  # OH encoding voor categorische features
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

model = Pipeline([
    ('preprocessor', preprocessor),  # Preprocessing steps
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))  # RandomForest Classifier
])
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluatie
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Accuracy: 0.96
Confusion Matrix:
[[14231   297]
 [  629 10736]]
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.98      0.97     14528
           1       0.97      0.94      0.96     11365

    accuracy                           0.96     25893
   macro avg       0.97      0.96      0.96     25893
weighted avg       0.96      0.96      0.96     25893